# Generated by Django 6.1 on 2026-08-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('establishment_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('reference_contact_name', models.CharField(max_length=255)),
                ('reference_contact_phone', models.CharField(max_length=15)),
                ('reference_role', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verification_notes', models.TextField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='accounts.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_access_logs', to='accounts.employerprofile')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_unlocks', to='payments.transaction')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_access_logs', to='accounts.workerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employer', 'worker'), name='unique_history_access_per_employer_worker')],
            },
        ),
    ]
