# Generated by Django 6.1 on 2026-08-30 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employerprofile_establishments'),
        ('employment_history', '0007_employmentrecord_employer_and_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentrecord',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records_added', to='accounts.employerprofile'),
        ),
    ]
