# Generated by Django 6.1 on 2026-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('registered_workers', models.PositiveIntegerField(default=0)),
                ('active_employers', models.PositiveIntegerField(default=0)),
                ('jobs_posted', models.PositiveIntegerField(default=0)),
                ('applications', models.PositiveIntegerField(default=0)),
                ('successful_hires', models.PositiveIntegerField(default=0)),
                ('paid_unlocks', models.PositiveIntegerField(default=0)),
                ('premium_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_revenue_per_paying_employer_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repeat_employer_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('customer_acquisition_cost_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_kpi_snapshot_period')],
            },
        ),
    ]
