# Generated by Django 6.1 on 2026-08-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_kpi_snapshot_period_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kpisnapshot',
            new_name='analytics_k_period__065270_idx',
            old_name='analytics_period_end_idx',
        ),
    ]
