import { useState } from 'react'
import { ArrowRight, BadgeCheck, Briefcase, Building2, CheckCircle2, PlusCircle, Star, Users } from 'lucide-react'
import { Link, Navigate } from 'react-router-dom'
import { useAuthStore } from '../../auth'
import { StatCard } from '../../../shared/components/cards/StatCard'
import { EmptyState } from '../../../shared/components/feedback'
import { PieChart } from '../../../shared/components/charts'
import { DataTable } from '../../../shared/components/tables'
import { Skeleton, Tabs } from '../../../shared/components/ui'
import { PageHeader } from '../../../shared/components/ui/PageHeader'
import { useDashboard } from '../hooks'
import { getTimeGreeting } from '../../../core/utils'

export function EmployerDashboardPage() {
  const { user } = useAuthStore()
  const { data, loading, error, refresh } = useDashboard()
  const [activeTab, setActiveTab] = useState<'jobs' | 'applicants' | 'venues'>('jobs')
  const [filter, setFilter] = useState<'all' | 'open' | 'urgent'>('all')
  const jobs = data?.jobs ?? []
  const applications = data?.applications ?? []
  const establishments = data?.establishments ?? []
  const employerProfile = data?.employerProfile
  if (user?.is_worker && !user.is_employer) return <Navigate to="/dashboard/worker" replace />
  const openJobs = jobs.filter((job) => job.status === 'open')
  const urgentJobs = jobs.filter((job) => job.is_urgent)
  const hired = applications.filter((application) => application.status === 'hired').length
  const visibleJobs = jobs.filter((job) => filter === 'all' || filter === 'open' ? filter === 'all' ? true : job.status === 'open' : job.is_urgent)

  return <section className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <PageHeader title={`${getTimeGreeting()}, ${user?.full_name?.split(' ')[0] || 'Partner'}!`} description="Manage your hospitality shifts, review verified Kenyan talent passports, and confirm immediate bookings. Shift dispatch is active." actions={<div className="flex w-full flex-col gap-2 sm:w-auto"><div className="flex w-full flex-nowrap gap-2"><Link to="/workers" className="inline-flex min-h-[44px] min-w-0 flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-xl border border-white/20 bg-white/10 px-3.5 py-2.5 text-xs font-bold text-white"><Users className="h-4 w-4 shrink-0 text-[#FF6B00]" />Search talent</Link><Link to="/jobs/new" className="inline-flex min-h-[44px] min-w-0 flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-xl bg-[#FF6B00] px-4 py-2.5 text-sm font-bold text-white"><PlusCircle className="h-4 w-4 shrink-0" />Post a shift</Link></div><RatingRow rating={employerProfile?.average_rating} reviews={employerProfile?.reviews_count} /></div>} />
    {loading ? <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-32 rounded-2xl" />)}</div> : <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard title="Open shift roles" value={openJobs.length} subtitle={`${urgentJobs.length} marked urgent`} badge={{ text: `${urgentJobs.length} urgent`, variant: 'orange' }} sparkline={[4, 6, 8, 7, 10, 9, Math.max(openJobs.length, 6)]} icon={<Briefcase className="h-5 w-5" />} iconBg="bg-orange-50 text-[#FF6B00]" /><StatCard title="Active applicants" value={applications.length} subtitle="Candidates in pipeline" icon={<Users className="h-5 w-5" />} iconBg="bg-blue-50 text-blue-600" /><StatCard title="Connected venues" value={establishments.length} subtitle="Verified outlets" icon={<Building2 className="h-5 w-5" />} iconBg="bg-amber-50 text-amber-600" /><StatCard title="Completed hires" value={hired} subtitle="Successful placements" progress={{ value: 99.2, max: 100, label: 'Attendance rate', color: '#059669' }} icon={<CheckCircle2 className="h-5 w-5" />} iconBg="bg-emerald-50 text-emerald-600" /></div>}
    <div className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-sm font-bold text-emerald-950">Shift payment readiness</h3><p className="mt-1 text-xs text-emerald-800">Review shift details and confirm payment before work begins.</p></div><Link to="/jobs/new" className="inline-flex min-h-[38px] items-center justify-center rounded-xl bg-emerald-700 px-3.5 py-2 text-xs font-bold text-white">Plan next shift</Link></div></div>
    <div className="flex flex-col gap-4"><div className="flex items-center justify-between gap-4 border-b border-slate-200 pb-3"><Tabs variant="segmented" activeTab={activeTab} onChange={(tab) => setActiveTab(tab as typeof activeTab)} tabs={[{ id: 'jobs', label: 'Job shifts', badge: jobs.length, badgeVariant: 'orange', icon: Briefcase }, { id: 'applicants', label: 'Candidate pipeline', badge: applications.length, badgeVariant: 'neutral', icon: Users }, { id: 'venues', label: 'Outlets & venues', badge: establishments.length, badgeVariant: 'primary', icon: Building2 }]} /><button type="button" onClick={() => refresh()} className="hidden rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-slate-500 sm:inline-flex">Refresh data</button></div>{error && <p className="text-sm text-rose-600">{error}</p>}
      {activeTab === 'jobs' && <div className="grid gap-6 lg:grid-cols-[1.5fr_0.8fr]"><div className="min-w-0 space-y-4"><div className="flex items-center gap-2 overflow-x-auto">{(['all', 'open', 'urgent'] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-xs font-bold ${filter === item ? 'bg-[#FF6B00] text-white' : 'bg-slate-100 text-slate-600'}`}>{item}</button>)}<Link to="/jobs/new" className="ml-auto whitespace-nowrap text-xs font-bold text-[#FF6B00]">+ New shift</Link></div><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:block"><DataTable data={visibleJobs} keyExtractor={(job) => String(job.id)} emptyMessage="No jobs match the filter." columns={[{ header: 'Role', render: (job) => <Link to={`/jobs/${job.id}`} className="font-bold text-slate-900 hover:text-[#FF6B00]">{job.title}</Link> }, { header: 'Location', accessor: 'location' }, { header: 'Pay', render: (job) => <span className="text-xs font-black">KSh {job.pay_amount_ksh.toLocaleString()} / {job.pay_period}</span> }, { header: 'Applicants', accessor: 'applicant_count' }, { header: 'Status', render: (job) => <span className="rounded-md bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">{job.status}</span> }]} /></div><div className="space-y-3 sm:hidden">{visibleJobs.map((job) => <div key={job.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate text-sm font-bold text-slate-900">{job.title}</h3><p className="mt-1 text-xs text-slate-500">{job.location}</p></div><span className="shrink-0 text-xs font-black text-[#0A2540]">KSh {job.pay_amount_ksh.toLocaleString()}</span></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-2 text-xs"><span className="font-semibold text-slate-600">{job.applicant_count} applicants</span><Link to={`/jobs/${job.id}`} className="rounded-lg bg-[#0A2540] px-3 py-1.5 font-bold text-white">Manage role</Link></div></div>)}{!visibleJobs.length && <EmptyState title="No jobs found" description="Post a shift to start hiring." size="sm" />}</div></div><PieChart title="Applicant distribution" subtitle="Status of active candidates" data={[{ label: 'Applied', value: applications.filter((item) => item.status === 'applied').length, color: '#0A2540' }, { label: 'Shortlisted', value: applications.filter((item) => item.status === 'shortlisted').length, color: '#FF6B00' }, { label: 'Hired', value: hired, color: '#059669' }]} /></div>}
      {activeTab === 'applicants' && <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Candidate applications ({applications.length})</h2><p className="mt-1 text-xs text-slate-500">Screen talent, view passports, and confirm shifts.</p></div><Link to="/workers" className="text-xs font-bold text-[#FF6B00]">Search candidates</Link></div><div className="mt-4 space-y-3">{applications.map((application) => <div key={application.id} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm">{application.worker_name || `Applicant #${application.worker}`}</strong><span className="ml-2 inline-flex items-center gap-1 rounded-md bg-emerald-50 px-1.5 py-0.5 text-[10px] font-bold text-emerald-700"><BadgeCheck className="h-3 w-3" />ID verified</span><p className="mt-1 text-xs text-slate-600">Applied for: {application.job_title}</p></div><div className="flex gap-2"><Link to="/messages" className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold">Chat</Link><Link to={`/jobs/${application.job}`} className="rounded-lg bg-[#0A2540] px-3 py-1.5 text-xs font-bold text-white">Review</Link></div></div></div>)}{!applications.length && <EmptyState title="No applications yet" description="Applications will appear when candidates apply." action={<Link to="/jobs/new" className="btn-primary-orange inline-flex text-xs">Post a shift</Link>} size="sm" />}</div></div>}
      {activeTab === 'venues' && <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Establishment locations ({establishments.length})</h2><p className="mt-1 text-xs text-slate-500">Branches and venues managed under your account.</p></div><Link to="/establishments" className="text-xs font-bold text-[#FF6B00]">Manage establishments</Link></div><div className="mt-4 grid gap-4 sm:grid-cols-2">{establishments.map((establishment) => <div key={establishment.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><strong className="flex items-center gap-2 text-sm"><Building2 className="h-4 w-4 text-[#FF6B00]" />{establishment.name}</strong>{establishment.is_verified && <BadgeCheck className="h-4 w-4 text-emerald-600" />}</div><p className="mt-2 text-xs text-slate-500">{establishment.location || establishment.address}</p><Link to="/jobs/new" className="mt-3 inline-flex items-center text-xs font-bold text-[#0A2540]">Post for this branch <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></div>)}{!establishments.length && <EmptyState title="No establishments registered" description="Add your first venue." action={<Link to="/establishments" className="btn-primary-orange inline-flex text-xs">Add establishment</Link>} size="sm" />}</div></div>}
    </div>
  </section>
}

function RatingRow({ rating, reviews }: { rating?: number | string; reviews?: number }) {
  const score = Number(rating || 0)
  return <div className="flex items-center justify-end gap-2 text-xs text-slate-300" aria-label={`${score.toFixed(1)} out of 5 stars from ${reviews || 0} reviews`}><span className="flex items-center gap-0.5">{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`h-3.5 w-3.5 ${index < Math.round(score) ? 'fill-amber-400 text-amber-400' : 'text-slate-500'}`} />)}</span><span>{score.toFixed(1)} · {reviews || 0} reviews</span></div>
}
