# Generated by Django 6.1 on 2026-08-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_ticket_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_user_id_170a74_idx',
            old_name='support_use_status_7d1c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_status_b6136a_idx',
            old_name='support_status_5a9b3e_idx',
        ),
    ]
