import { useState } from 'react'
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react'

const FAQS = [['Who is KaziLink for?', 'Employers can find workers for hospitality, domestic, technical, care, logistics, and other service roles. Workers can build a profile and discover opportunities that fit their skills and availability.'], ['Is creating a worker profile free?', 'Yes. Workers can create a profile, add skills and availability, and apply for suitable opportunities. Optional platform actions may use Kazi Credits.'], ['How do referrals work?', 'Share your personal referral code. When the new user verifies their phone, both accounts can receive the configured Kazi Credits reward.'], ['How are roles and availability selected?', 'The role and availability catalog comes from the KaziLink backend, so the choices can grow as the marketplace grows.'], ['What can employers see?', 'Employers can review the information made available by workers, including role, skills, availability, and verified history where access has been granted.']]

export function FaqSection() {
  const [open, setOpen] = useState(0)
  return <section className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><div className="text-center"><div className="inline-flex items-center gap-1.5 rounded-full bg-[#FF6B00]/10 px-3 py-1 text-xs font-bold text-[#FF6B00]"><HelpCircle className="h-3.5 w-3.5" />Questions, answered</div><h2 className="mt-3 text-2xl font-black text-slate-900 sm:text-3xl">Start with clarity</h2></div><div className="mt-10 space-y-3">{FAQS.map(([question, answer], index) => <div key={question} className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50/70"><button type="button" onClick={() => setOpen(open === index ? -1 : index)} className="flex w-full items-center justify-between gap-4 p-4 text-left text-sm font-bold text-slate-900 sm:p-5"><span>{question}</span>{open === index ? <ChevronUp className="h-4 w-4 shrink-0 text-[#FF6B00]" /> : <ChevronDown className="h-4 w-4 shrink-0 text-slate-400" />}</button>{open === index && <div className="border-t border-slate-200/70 bg-white p-4 text-sm leading-relaxed text-slate-600 sm:p-5">{answer}</div>}</div>)}</div></div></section>
}
