import { useState } from 'react'
import { ArrowRight, Calculator, CheckCircle2, Clock3, TrendingUp, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'

export function ShiftRoiCalculator() {
  const [shifts, setShifts] = useState(20)
  const hours = Math.round(shifts * 1.6)
  const protectedValue = shifts * 1650
  return <section className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 rounded-3xl border border-slate-200 bg-gradient-to-br from-slate-50 via-white to-orange-50/30 p-6 shadow-sm sm:p-10 lg:grid-cols-[1fr_1.1fr] lg:p-12"><div><div className="inline-flex items-center gap-2 rounded-full bg-[#FF6B00]/10 px-3 py-1 text-xs font-bold text-[#FF6B00]"><Calculator className="h-3.5 w-3.5" />Venue efficiency</div><h2 className="mt-3 text-2xl font-black text-slate-900 sm:text-3xl">Make every shift easier to fill.</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">Estimate the time your team can recover when role, pay, availability, and expectations are clear from the beginning.</p><div className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><label htmlFor="shifts-range" className="text-xs font-bold uppercase tracking-wider text-slate-700">Monthly shifts</label><span className="text-2xl font-black text-[#FF6B00]">{shifts}</span></div><input id="shifts-range" type="range" min="4" max="100" step="2" value={shifts} onChange={(event) => setShifts(Number(event.target.value))} className="mt-4 h-2 w-full accent-[#FF6B00]" /><div className="mt-2 flex justify-between text-[11px] text-slate-400"><span>Small team</span><span>Busy venue</span><span>Large operation</span></div></div><div className="mt-5 flex items-center gap-2 text-xs text-slate-600"><CheckCircle2 className="h-4 w-4 text-emerald-600" />Clear information means fewer wasted conversations.</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-md"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Estimated monthly impact</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-slate-500"><Clock3 className="h-4 w-4 text-[#0A2540]" /><span className="text-xs font-bold">Manager time saved</span></div><p className="mt-2 text-3xl font-black text-[#0A2540]">~{hours} hrs</p></div><div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-slate-500"><TrendingUp className="h-4 w-4 text-[#FF6B00]" /><span className="text-xs font-bold">Value protected</span></div><p className="mt-2 text-3xl font-black text-[#FF6B00]">KSh {protectedValue.toLocaleString()}</p></div></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><Zap className="h-5 w-5 text-emerald-600" /><p className="text-xs font-semibold text-emerald-900">Use availability and role filters to reach the right people faster.</p></div><Link to="/register" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#0A2540] px-4 py-3 text-xs font-bold text-white transition hover:bg-[#FF6B00]">Start hiring <ArrowRight className="h-3.5 w-3.5" /></Link></div></div></div></section>
}
