# Generated by Django 6.1 on 2026-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('establishment_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
