WORKER_OCCUPATIONS = (
	('nanny', 'Nanny / Childcare provider'),
	('housekeeper', 'Housekeeper'),
	('cleaner', 'Cleaner'),
	('caregiver', 'Caregiver'),
	('cook', 'Cook / Chef'),
	('waiter', 'Waiter / Waitress'),
	('bartender', 'Bartender'),
	('barista', 'Barista'),
	('receptionist', 'Receptionist'),
	('security_guard', 'Security guard'),
	('driver', 'Driver'),
	('gardener', 'Gardener'),
	('laundry_attendant', 'Laundry attendant'),
	('salon_shampooist', 'Shampooist / Salon assistant'),
	('hairdresser', 'Hairdresser / Stylist'),
	('barber', 'Barber'),
	('makeup_artist', 'Makeup artist'),
	('nail_technician', 'Nail technician'),
	('masseuse', 'Massage therapist'),
	('event_staff', 'Event staff'),
	('shop_attendant', 'Shop attendant'),
	('house_manager', 'House manager'),
	('personal_assistant', 'Personal assistant'),
	('office_cleaner', 'Office cleaner'),
	('dishwasher', 'Dishwasher / Kitchen assistant'),
	('pastry_baker', 'Baker / Pastry assistant'),
	('host_hostess', 'Host / Hostess'),
	('front_desk_agent', 'Front desk agent'),
	('room_attendant', 'Hotel room attendant'),
	('bellhop', 'Bellhop / Porter'),
	('catering_staff', 'Catering staff'),
	('event_coordinator', 'Event coordinator'),
	('photographer', 'Photographer'),
	('videographer', 'Videographer'),
	('tailor', 'Tailor / Dressmaker'),
	('seamstress', 'Seamstress'),
	('shoe_care_attendant', 'Shoe care attendant'),
	('car_wash_attendant', 'Car wash attendant'),
	('delivery_rider', 'Delivery rider'),
	('warehouse_assistant', 'Warehouse assistant'),
	('sales_attendant', 'Sales attendant'),
	('cashier', 'Cashier'),
	('plumber', 'Plumber'),
	('electrician', 'Electrician'),
	('mason', 'Mason / Block layer'),
	('carpenter', 'Carpenter'),
	('steel_fixer', 'Steel fixer / Rebar worker'),
	('tile_fixer', 'Tile fixer'),
	('painter', 'Painter / Decorator'),
	('welder', 'Welder / Fabricator'),
	('ac_technician', 'Air conditioning technician'),
	('refrigeration_technician', 'Refrigeration technician'),
	('hvac_technician', 'HVAC technician'),
	('generator_mechanic', 'Generator mechanic'),
	('motor_vehicle_mechanic', 'Motor vehicle mechanic'),
	('auto_electrician', 'Auto electrician'),
	('heavy_equipment_operator', 'Heavy equipment operator'),
	('crane_operator', 'Crane operator'),
	('forklift_operator', 'Forklift operator'),
	('scaffolder', 'Scaffolder'),
	('glazier', 'Glazier / Glass installer'),
	('aluminium_fabricator', 'Aluminium fabricator'),
	('waterproofing_worker', 'Waterproofing worker'),
	('road_worker', 'Road construction worker'),
	('general_construction_worker', 'General construction worker'),
	('farm_worker', 'Farm worker'),
	('animal_attendant', 'Animal attendant / Groom'),
	('fish_cleaner', 'Fish cleaner / Seafood worker'),
	('warehouse_worker', 'Warehouse worker'),
	('storekeeper', 'Storekeeper'),
	('logistics_coordinator', 'Logistics coordinator'),
	('truck_driver', 'Truck driver'),
	('bus_driver', 'Bus driver'),
	('personal_driver', 'Personal driver'),
	('motorcycle_rider', 'Motorcycle rider'),
	('security_supervisor', 'Security supervisor'),
	('watchman', 'Watchman'),
	('elderly_caregiver', 'Elderly caregiver'),
	('special_needs_caregiver', 'Special needs caregiver'),
	('home_nurse', 'Home nurse'),
	('midwife', 'Midwife'),
	('barber_supervisor', 'Barber shop supervisor'),
	('salon_supervisor', 'Salon supervisor'),
	('beauty_therapist', 'Beauty therapist'),
	('spa_therapist', 'Spa therapist'),
	('hotel_supervisor', 'Hotel supervisor'),
	('restaurant_supervisor', 'Restaurant supervisor'),
	('chef_de_partie', 'Chef de partie'),
	('kitchen_supervisor', 'Kitchen supervisor'),
	('food_packer', 'Food packer'),
	('barista_supervisor', 'Barista supervisor'),
	('english_tutor', 'English tutor'),
	('private_tutor', 'Private tutor'),
	('other', 'Other hospitality or domestic role'),
)

WORKER_AVAILABILITIES = (
	('immediate', 'Immediate'),
	('full_time', 'Full time'),
	('part_time', 'Part time'),
	('weekends', 'Weekends'),
	('weekdays', 'Weekdays'),
	('night_shifts', 'Night shifts'),
	('day_shifts', 'Day shifts'),
	('flexible', 'Flexible schedule'),
)


def worker_occupation_catalog():
	return [{'value': value, 'label': label} for value, label in WORKER_OCCUPATIONS]


def worker_availability_catalog():
	return [{'value': value, 'label': label} for value, label in WORKER_AVAILABILITIES]
