WORKER_OCCUPATIONS = (
	('nanny', 'Nanny / Childcare provider'),
	('housekeeper', 'Housekeeper'),
	('cleaner', 'Cleaner'),
	('mama_fua', 'Mama fua / Laundry service provider'),
	('caregiver', 'Caregiver'),
	('cook', 'Cook / Chef'),
	('waiter', 'Waiter / Waitress'),
	('bartender', 'Bartender'),
	('barista', 'Barista'),
	('receptionist', 'Receptionist'),
	('security_guard', 'Security guard'),
	('driver', 'Driver'),
	('gardener', 'Gardener'),
	('laundry_attendant', 'Laundry attendant'),
	('salon_shampooist', 'Shampooist / Salon assistant'),
	('hairdresser', 'Hairdresser / Stylist'),
	('barber', 'Barber'),
	('makeup_artist', 'Makeup artist'),
	('nail_technician', 'Nail technician'),
	('masseuse', 'Massage therapist'),
	('event_staff', 'Event staff'),
	('shop_attendant', 'Shop attendant'),
	('house_manager', 'House manager'),
	('personal_assistant', 'Personal assistant'),
	('office_cleaner', 'Office cleaner'),
	('dishwasher', 'Dishwasher / Kitchen assistant'),
	('pastry_baker', 'Baker / Pastry assistant'),
	('host_hostess', 'Host / Hostess'),
	('front_desk_agent', 'Front desk agent'),
	('room_attendant', 'Hotel room attendant'),
	('bellhop', 'Bellhop / Porter'),
	('catering_staff', 'Catering staff'),
	('event_coordinator', 'Event coordinator'),
	('photographer', 'Photographer'),
	('videographer', 'Videographer'),
	('tailor', 'Tailor / Dressmaker'),
	('seamstress', 'Seamstress'),
	('shoe_care_attendant', 'Shoe care attendant'),
	('car_wash_attendant', 'Car wash attendant'),
	('delivery_rider', 'Delivery rider'),
	('warehouse_assistant', 'Warehouse assistant'),
	('sales_attendant', 'Sales attendant'),
	('cashier', 'Cashier'),
	('plumber', 'Plumber'),
	('electrician', 'Electrician'),
	('mason', 'Mason / Block layer'),
	('carpenter', 'Carpenter'),
	('steel_fixer', 'Steel fixer / Rebar worker'),
	('tile_fixer', 'Tile fixer'),
	('painter', 'Painter / Decorator'),
	('welder', 'Welder / Fabricator'),
	('ac_technician', 'Air conditioning technician'),
	('refrigeration_technician', 'Refrigeration technician'),
	('hvac_technician', 'HVAC technician'),
	('generator_mechanic', 'Generator mechanic'),
	('motor_vehicle_mechanic', 'Motor vehicle mechanic'),
	('auto_electrician', 'Auto electrician'),
	('heavy_equipment_operator', 'Heavy equipment operator'),
	('crane_operator', 'Crane operator'),
	('forklift_operator', 'Forklift operator'),
	('scaffolder', 'Scaffolder'),
	('glazier', 'Glazier / Glass installer'),
	('aluminium_fabricator', 'Aluminium fabricator'),
	('waterproofing_worker', 'Waterproofing worker'),
	('road_worker', 'Road construction worker'),
	('general_construction_worker', 'General construction worker'),
	('farm_worker', 'Farm worker'),
	('animal_attendant', 'Animal attendant / Groom'),
	('fish_cleaner', 'Fish cleaner / Seafood worker'),
	('warehouse_worker', 'Warehouse worker'),
	('storekeeper', 'Storekeeper'),
	('logistics_coordinator', 'Logistics coordinator'),
	('truck_driver', 'Truck driver'),
	('bus_driver', 'Bus driver'),
	('personal_driver', 'Personal driver'),
	('motorcycle_rider', 'Motorcycle rider'),
	('security_supervisor', 'Security supervisor'),
	('watchman', 'Watchman'),
	('elderly_caregiver', 'Elderly caregiver'),
	('special_needs_caregiver', 'Special needs caregiver'),
	('home_nurse', 'Home nurse'),
	('midwife', 'Midwife'),
	('barber_supervisor', 'Barber shop supervisor'),
	('salon_supervisor', 'Salon supervisor'),
	('beauty_therapist', 'Beauty therapist'),
	('spa_therapist', 'Spa therapist'),
	('hotel_supervisor', 'Hotel supervisor'),
	('restaurant_supervisor', 'Restaurant supervisor'),
	('chef_de_partie', 'Chef de partie'),
	('kitchen_supervisor', 'Kitchen supervisor'),
	('food_packer', 'Food packer'),
	('barista_supervisor', 'Barista supervisor'),
	('english_tutor', 'English tutor'),
	('private_tutor', 'Private tutor'),
	('other', 'Other hospitality or domestic role'),
)

WORKER_AVAILABILITIES = (
	('immediate', 'Immediate'),
	('full_time', 'Full time'),
	('part_time', 'Part time'),
	('weekends', 'Weekends'),
	('weekdays', 'Weekdays'),
	('night_shifts', 'Night shifts'),
	('day_shifts', 'Day shifts'),
	('flexible', 'Flexible schedule'),
)

WORKER_SKILLS = (
	('customer_service', 'Customer service'),
	('food_preparation', 'Food preparation'),
	('food_safety', 'Food safety and hygiene'),
	('menu_planning', 'Menu planning'),
	('table_service', 'Table service'),
	('bar_service', 'Bar service'),
	('coffee_preparation', 'Coffee preparation'),
	('cash_handling', 'Cash handling'),
	('point_of_sale', 'Point of sale systems'),
	('stock_control', 'Stock control'),
	('inventory_management', 'Inventory management'),
	('housekeeping', 'Housekeeping'),
	('deep_cleaning', 'Deep cleaning'),
	('laundry', 'Laundry'),
	('ironing', 'Ironing'),
	('childcare', 'Childcare'),
	('elderly_care', 'Elderly care'),
	('first_aid', 'First aid'),
	('patient_support', 'Patient support'),
	('driving', 'Driving'),
	('defensive_driving', 'Defensive driving'),
	('route_planning', 'Route planning'),
	('security_monitoring', 'Security monitoring'),
	('access_control', 'Access control'),
	('cctv_monitoring', 'CCTV monitoring'),
	('event_setup', 'Event setup'),
	('event_coordination', 'Event coordination'),
	('sales', 'Sales'),
	('merchandising', 'Merchandising'),
	('cashier_operations', 'Cashier operations'),
	('computer_literacy', 'Computer literacy'),
	('microsoft_office', 'Microsoft Office'),
	('communication', 'Written and verbal communication'),
	('team_leadership', 'Team leadership'),
	('time_management', 'Time management'),
	('problem_solving', 'Problem solving'),
	('plumbing', 'Plumbing'),
	('electrical_repair', 'Electrical repair'),
	('carpentry', 'Carpentry'),
	('painting', 'Painting and decorating'),
	('welding', 'Welding'),
	('masonry', 'Masonry'),
	('tile_work', 'Tile work'),
	('motor_vehicle_repair', 'Motor vehicle repair'),
	('beauty_services', 'Beauty services'),
	('hair_styling', 'Hair styling'),
	('makeup', 'Makeup application'),
	('massage', 'Massage therapy'),
	('tailoring', 'Tailoring'),
	('photography', 'Photography'),
	('video_production', 'Video production'),
	('social_media', 'Social media management'),
)

EMPLOYER_BUSINESS_TYPES = (
	('hotel', 'Hotel'),
	('restaurant', 'Restaurant'),
	('cafe', 'Cafe / Coffee shop'),
	('bar_lounge', 'Bar / Lounge'),
	('catering', 'Catering business'),
	('event_company', 'Events company'),
	('domestic_services', 'Domestic services'),
	('cleaning_services', 'Cleaning services'),
	('security_services', 'Security services'),
	('retail', 'Retail business'),
	('salon_spa', 'Salon / Spa'),
	('construction', 'Construction company'),
	('logistics', 'Logistics company'),
	('healthcare', 'Healthcare provider'),
	('education', 'Education provider'),
	('other', 'Other'),
)

WORK_LOCATIONS = (
	('Nairobi', 'Nairobi'),
	('Mombasa', 'Mombasa'),
	('Kisumu', 'Kisumu'),
	('Nakuru', 'Nakuru'),
	('Eldoret', 'Eldoret'),
	('Thika', 'Thika'),
	('Malindi', 'Malindi'),
	('Kitale', 'Kitale'),
	('Garissa', 'Garissa'),
	('Kakamega', 'Kakamega'),
	('Nyeri', 'Nyeri'),
	('Machakos', 'Machakos'),
	('Meru', 'Meru'),
	('Naivasha', 'Naivasha'),
	('Embu', 'Embu'),
	('Nanyuki', 'Nanyuki'),
	('Kericho', 'Kericho'),
	('Bungoma', 'Bungoma'),
	('Busia', 'Busia'),
	('Homa Bay', 'Homa Bay'),
	('Kisii', 'Kisii'),
	('Kitui', 'Kitui'),
	('Lodwar', 'Lodwar'),
	('Isiolo', 'Isiolo'),
	('Moyale', 'Moyale'),
	('Voi', 'Voi'),
	('Wajir', 'Wajir'),
	('Mandera', 'Mandera'),
	('Bomet', 'Bomet'),
	('Narok', 'Narok'),
	('Bahrain - Manama', 'Bahrain - Manama'),
	('Kuwait - Kuwait City', 'Kuwait - Kuwait City'),
	('Oman - Muscat', 'Oman - Muscat'),
	('Oman - Salalah', 'Oman - Salalah'),
	('Qatar - Doha', 'Qatar - Doha'),
	('Saudi Arabia - Riyadh', 'Saudi Arabia - Riyadh'),
	('Saudi Arabia - Jeddah', 'Saudi Arabia - Jeddah'),
	('Saudi Arabia - Dammam', 'Saudi Arabia - Dammam'),
	('Saudi Arabia - Mecca', 'Saudi Arabia - Mecca'),
	('Saudi Arabia - Medina', 'Saudi Arabia - Medina'),
	('United Arab Emirates - Dubai', 'United Arab Emirates - Dubai'),
	('United Arab Emirates - Abu Dhabi', 'United Arab Emirates - Abu Dhabi'),
	('United Arab Emirates - Sharjah', 'United Arab Emirates - Sharjah'),
	('United Arab Emirates - Ajman', 'United Arab Emirates - Ajman'),
	('United Arab Emirates - Ras Al Khaimah', 'United Arab Emirates - Ras Al Khaimah'),
	('United Arab Emirates - Fujairah', 'United Arab Emirates - Fujairah'),
)


def worker_occupation_catalog():
	return [{'value': value, 'label': label} for value, label in WORKER_OCCUPATIONS]


def worker_availability_catalog():
	return [{'value': value, 'label': label} for value, label in WORKER_AVAILABILITIES]


def worker_location_catalog():
	return [{'value': value, 'label': label} for value, label in WORK_LOCATIONS]


def worker_skill_catalog():
	return [{'value': value, 'label': label} for value, label in WORKER_SKILLS]


def employer_business_type_catalog():
	return [{'value': value, 'label': label} for value, label in EMPLOYER_BUSINESS_TYPES]
