# Generated by Django 6.1 on 2026-08-28 23:36

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_search_document'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_status_posted_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
